// export const templatePaths = {
//     REACT: "/starters/react-ts",
//     NEXTJS: "/starters/nextjs-new",
//     EXPRESS: "/starters/express-simple",
//     VUE: "/starters/vue",
//     HONO: "/starters/hono-nodejs-starter",
//     ANGULAR: "/starters/angular",

// };


export const templatePaths = {
  ANGULAR: "/starters/angular",
  ASTRO_SHADCN: "/starters/astro-shadcn",
  BOLT_EXPO: "/starters/bolt-expo",
  BOLT_QWIK: "/starters/bolt-qwik",
  BOLT_REMOTION: "/starters/bolt-remotion",
  BOLT_VITE_REACT_TS: "/starters/bolt-vite-react-ts",
  BOOTSTRAP_5: "/starters/bootstrap-5",
  EGG: "/starters/egg",
  EXPRESS_SIMPLE: "/starters/express-simple",
  GRAPHQL: "/starters/graphql",
  GSAP_NEXT: "/starters/gsap-next",
  GSAP_NUXT: "/starters/gsap-nuxt",
  GSAP_REACT: "/starters/gsap-react",
  GSAP_SVELTE: "/starters/gsap-svelte",
  GSAP_SVELTEKIT: "/starters/gsap-sveltekit",
  GSAP_VUE: "/starters/gsap-vue",
  HONO_NODEJS_STARTER: "/starters/hono-nodejs-starter",
  JS: "/starters/js",
  JSON_GRAPHQL_SERVER: "/starters/json-graphql-server",
  JSON_SERVER: "/starters/json-server",
  KOA: "/starters/koa",
  NEXTJS_SHADCN: "/starters/nextjs-shadcn",
  NEXTJS: "/starters/nextjs",
  NODE: "/starters/node",
  NODEMON: "/starters/nodemon",
  QUASAR: "/starters/quasar",
  REACT_TS: "/starters/react-ts",
  REACT: "/starters/react",
  RXJS: "/starters/rxjs",
  SLIDEV: "/starters/slidev",
  STATIC: "/starters/static",
  SVELTEKIT: "/starters/sveltekit",
  TEST: "/starters/test",
  TRES: "/starters/tres",
  TUTORIALKIT: "/starters/tutorialkit",
  TYPESCRIPT: "/starters/typescript",
  VITE_SHADCN: "/starters/vite-shadcn",
  VUE: "/starters/vue",
  WEB_PLATFORM: "/starters/web-platform",
  EXPRESS_JS: "/starters/express-js",
  PYTHON: "/starters/python-starter",

};

export const templateKeys = {
  angular: "ANGULAR",
  astro: "ASTRO_SHADCN",
  boltExpo: "BOLT_EXPO",
  boltQwik: "BOLT_QWIK",
  boltRemotion: "BOLT_REMOTION",
  boltViteReactTs: "BOLT_VITE_REACT_TS",
  bootstrap: "BOOTSTRAP_5",
  egg: "EGG",
  express: "EXPRESS_SIMPLE",
  expressjs: "EXPRESS_JS",
  graphql: "GRAPHQL",
  gsapNext: "GSAP_NEXT",
  gsapNuxt: "GSAP_NUXT",
  gsapReact: "GSAP_REACT",
  gsapSvelte: "GSAP_SVELTE",
  gsapSveltekit: "GSAP_SVELTEKIT",
  gsapVue: "GSAP_VUE",
  hono: "HONO_NODEJS_STARTER",
  js: "JS",
  jsonGraphql: "JSON_GRAPHQL_SERVER",
  jsonServer: "JSON_SERVER",
  koa: "KOA",
  nextjsShadcn: "NEXTJS_SHADCN",
  nextjs: "NEXTJS",
  node: "NODE",
  nodemon: "NODEMON",
  quasar: "QUASAR",
  react: "REACT",
  reactTs: "REACT_TS",
  rxjs: "RXJS",
  slidev: "SLIDEV",
  static: "STATIC",
  sveltekit: "SVELTEKIT",
  test: "TEST",
  tres: "TRES",
  tutorialkit: "TUTORIALKIT",
  typescript: "TYPESCRIPT",
  viteShadcn: "VITE_SHADCN",
  vue: "VUE",
  webPlatform: "WEB_PLATFORM",
  python: "PYTHON"
};

export const perpous = {
  frontend: "frontend",
  backend: "backend",
  fullstack: "fullstack",
  general: "general"
} as const
