import Footer from "@/modules/home/components/footer";
import Header from "@/modules/home/components/header";
import { Metadata } from "next";
import { LightRays } from "@/components/ui/light-rays"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function HomeLayout({ children }: { children: React.ReactNode }) {
  return (
    <>
      {/* Header */}
      <Header />

      {/* Background */}
      <div className="fixed inset-0 -z-10 w-full h-full overflow-hidden bg-background">
        {/* <FlickeringGrid
          className="absolute inset-0 [mask-image:radial-gradient(600px_circle_at_center,white,transparent)]"
          squareSize={4}
          gridGap={6}
          color="#60A5FA"
          maxOpacity={0.5}
          flickerChance={0.1}
          height={1080} // just a fallback, won't matter since CSS stretches it
          width={1920}  // same — safe default
        /> */}
           <LightRays />   
      </div>

      {/* Main */}
      <main className="relative z-10">{children}</main>

      {/* Footer */}
      <Footer />
    </>
  );
}
