import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SessionWrapper from "./SessionWrapper";
import { ThemeProvider } from "@/components/providers/them-provider";
import { Toaster } from "@/components/ui/sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en"
      className="dark"
     style= {{ "color-scheme": "dark" }}
    >
  <body
    className={`${geistSans.variable} ${geistMono.variable} antialiased`}
  >
    <SessionWrapper>
      <ThemeProvider
        attribute="class"
        defaultTheme="system"
        enableSystem
        disableTransitionOnChange
      >

        <div className="flex flex-col min-h-screen">
          <Toaster />
          <div className="flex-1">
            {children}
          </div>
        </div>
      </ThemeProvider>
    </SessionWrapper>
  </body>
    </html >
  );
}
